<!doctype html>
<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html" charset="utf-8"/>
	<title>See where your data packets go | IXmaps</title>

	<!-- JAVA SCRIPT -->
	<script type="text/javascript" src="/js/prototype.js"></script>
	<script type="text/javascript" src="/js/scriptaculous.js?load=effects,builder"></script>
	<script type="text/javascript" src="/js/lightbox.js"></script>
	<script src="/js/index.js"></script>
	<script language="JavaScript" type="text/javascript">
	//--------------- LOCALIZEABLE GLOBALS ---------------
	var d=new Date();
	var monthname=new Array("January","February","March","April","May","June","July","August","September","October","November","December");
	//Ensure correct for language. English is "January 1, 2004"
	var TODAY = monthname[d.getMonth()] + " " + d.getDate() + ", " + d.getFullYear();
	//--------------- END LOCALIZEABLE ---------------
  	</script>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-24555700-1']);
	  _gaq.push(['_setDomainName', 'none']);
	  _gaq.push(['_setAllowLinker', true]);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
	<script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
	<script type="text/javascript">
	    $.noConflict();
	    // jquery and prototype fight for the $
	</script>

	<!-- STYLESHEETS -->
	<link rel="stylesheet" href="css/ix.css" type="text/css" />
	<link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="css/overwrites.css" type="text/css" media="screen" />
</head>

<body onload="initialize()">
<div id="wrapper"><!-- #wrapper -->
<header><!-- header -->
  <img src="images/headerimage.jpg" width="1000" height="138">
  <!-- <img src="images/headerimg.jpg" width="932" height="200" alt=""> header image -->
</header><!-- end of header -->

<?php include("includes/navigation.php"); ?>

<section id="main"><!-- #main content and sidebar area -->

<section id="container"><!-- #container -->
	<section id="content"><!-- #content -->
	<article id="tour-container">

		<h2>A brief overview of what we're currently interested in...</h2>
		<div class="tour-container">
			<div class="tour-img-container">
				<h5>Mapping How Data Travels</h5>
				<img class="tour-img" src="images/ShowcasePage_Mapping_How_Data_Travels.jpg"/>
			</div>
			<div class="tour-text-container">
				<p>As your data moves, it leaves behind information about where it has been. You can learn where your data travels using a tool called <a href="/faq.php#Traceroute">Traceroute</a>. IXmaps collects traceroute data generated by volunteers and then <a href="/technical">geolocates that information</a> in order to map how internet traffic actually travels the globe. The IXmaps database has <a href="/explore">thousands of routes that you can explore</a>.</p>
				<p>There are lots of ways for you to <a href="/explore">explore</a> the IXmaps database. You can see traceroutes <a class="explore-my-country-routes">from your country</a>, see traceroutes from <a class="explore-my-city-routes">from your city</a>, see <a class="explore-boomerang-routes">'boomerang' routes</a>, or learn <a href="/index">how to perform a custom search</a>.</p>
				<p>Interested in where your data packets travel? <a href="/contribute">Download and run our TRgen application</a>, then explore the <a href="/explore">IXmaps database</a> to see your results.</p>
			</div>
		</div>
		<div class="tour-container">
			<div class="tour-img-container">
				<h5>Tracking Internet Surveillance</h5>
				<img class="tour-img" src="images/ShowcasePage_Tracking_Internet_Surveillance.jpg"/>
			</div>
			<div class="tour-text-container">
				<p><a class="explore-target-route" data-route-id="1859">This is traceroute #1859</a>. TR1859 shows data packets travelling from a home computer in Toronto to the San Francisco Art Institute's website. Along this route, we see that the data passes through a known NSA surveillance site, AT&T's internet switching facility in San Francisco, located at 611 Folsom Street.At this site, a <a href="/faq.php#Splitter Cabinet (7th Floor)">splitter cabinet</a> has been installed to divert a copy of all gateway traffic to NSA computers for inspection.</p>
				<p>The NSA is strongly suspected of having installed similar spy rooms in 15-20 other cities across the United States, including Los Angeles, New York and Chicago. You can see the 18 U.S. cities we estimate are the most likely to contain NSA splitter operations by turning on the 'NSA layer" in the Map Options tab of the <a href="/explore">Explore page</a>. The IXmaps database contains <a class="explore-nsa-routes">hundreds of routes that pass through them</a>.</p>
				<p><a href="https://docs.google.com/spreadsheet/ccc?key=0Aiub6gMLPmfYdGp3VzBRWU1kSnNhbWNqaHRFVlNCcWc&authkey=CMeo8ZkG&hl=en_US&authkey=CMeo8ZkG#gid=0">See a summary of the evidence supporting our claims regarding the NSA</a></p>
			</div>
		</div>
		<div class="tour-container">
			<div class="tour-img-container">
				<h5>Canadian Network Sovereignty</h5>
				<img class="tour-img" src="images/ShowcasePage_Cdn_Network_Sovereignty.jpg"/>
			</div>
			<div class="tour-text-container">
				<p><a class="explore-target-route" data-route-id="3381">This is traceroute #3381</a>. TR3381 shows data packets travelling from a home computer in Toronto to a local news and entertainment website. Along this route, we see that <a href="/faq.php#Packet">packets</a> that begin and end in Toronto pass through Chicago and New York, two of the most strongly suspected NSA surveillance cities.</p>
				<p>As a result of many technical, economic and policy choices made principally by private corporations, Canadian internet traffic is often routed through the US, even when both origin and destination are within Canada. These "<a class="explore-boomerang-routes">boomerang routes</a>" prompt concerns regarding <a href="/sovereignty">Canadian network sovereignty</a>, since Canadians' <a href="/faq.php#Packet">packets</a> passing through routers in the US are subject to US jurisdiction, where Canadian legal and constitutional protections are absent, and are a risk of  warrantless state surveillance under provisions of Executive Order 12333, the USA Patriot Act or the FISA Amendments Act. The IXmaps database contains hundreds of examples of Canadian boomerang routes. <a class="explore-boomerang-routes">See examples here.</a></p>
			</div>
		</div>

	</article>
    </section><!-- end of #content -->
</section><!-- end of #container -->

</section><!-- end of #main content and sidebar-->

<footer>
	<?php include("includes/footer.php"); ?>
</footer>
</div><!-- #wrapper -->
</body>
</html>
