TRUNCATE privacy_scores;
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 577, 'Bell',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 577, 'Bell',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 577, 'Bell',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 812, 'Rogers',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 812, 'Rogers',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 812, 'Rogers',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 6327, 'Shaw',1, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 6327, 'Shaw',0.5, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 6327, 'Shaw',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 852, 'Telus',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 852, 'Telus',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 852, 'Telus',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 174, 'Cogent',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 5645, 'Teksavvy',1, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 5645, 'Teksavvy',0.5, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 5645, 'Teksavvy',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 5645, 'Teksavvy',0.5, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 5645, 'Teksavvy',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 5645, 'Teksavvy',0.5, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 5645, 'Teksavvy',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 5645, 'Teksavvy',1, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 5645, 'Teksavvy',1, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 5645, 'Teksavvy',0, 'AC');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 13768, 'Peer 1',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 13768, 'Peer 1',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 13768, 'Peer 1',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 11814, 'Distributel',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 11814, 'Distributel',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 11814, 'Distributel',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 11814, 'Distributel',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 11814, 'Distributel',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 11814, 'Distributel',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 11814, 'Distributel',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 11814, 'Distributel',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 11814, 'Distributel',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 11814, 'Distributel',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 11260, 'Eastlink',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 11260, 'Eastlink',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 11260, 'Eastlink',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 15290, 'MTS Allstream',0.5, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 15290, 'MTS Allstream',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (1, 5769, 'Videotron',1, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (2, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (3, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (4, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (5, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (6, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (7, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (8, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (9, 5769, 'Videotron',0, 'JO');
INSERT INTO privacy_scores (star_id, asn, carrier_name, score, created_by) VALUES (10, 5769, 'Videotron',0, 'JO');