#!/usr/bin/python
import sys, re, string, os, tempfile, shutil

origString = sys.argv[1]
newString = sys.argv[2]

# --- escape special characters ---
origString = re.sub(r"(\W)", r"\\\1", origString)     

# --- If first character is a word character, make it a word boundary ---
origString = re.sub (r"^(\w)", r"\\b\1", origString)  

# --- If last character is a word character, make it a word boundary ---
origString = re.sub (r"(\w)$", r"\1\\b", origString)

# --- Generalize spaces ---
origString = re.sub (r"\\ ", r"\\s{1,2}", origString)

# escape C-format characters
newString = re.sub (r"\\", r"\\\\", newString)        

print origString + "\t" 
print newString

compiledOrigString = re.compile(origString)

filesModified = 0

for name in sys.argv[3:]:
    tempFile = tempfile.mktemp()

    # --- Open files for input and output ---
    inp = open(name, 'r')
    output = open(tempFile, 'w')

    # --- Title file ---
    fileText = inp.read()

    #newText = re.subn (origString, newString, fileText)
    newText = compiledOrigString.subn (newString, fileText)
    if (not newText[1]):
        pass
    else:
        if (not filesModified):
            print "Files modified:"
            filesModified = 1
        print name
        inp.close

        inp = open (name, 'w')
        inp.write (newText[0])


if (not filesModified):
    print "no files modified"

